markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 
source: .

paginate: 8
paginate_path: "blog/page:num"

# presonal config
domain: gnyuan.github.io/blog/
title: Morgan's Blog
description: Android, Cocos2d, Java Web, Linux, reading...
author: Steven Pan
email: winfirm#163.com
github: panxw

config:
  js_dir:
  img_dir:
  css_dir:
